# Description: Sort method arguments to place required parameters before optional parameters.
sortParamsByRequiredFlag: true

# Description: Sort model properties to place required parameters before optional parameters.
sortModelPropertiesByRequiredFlag: true

# Description: Whether to ensure parameter names are unique in an operation (rename parameters that are not).
ensureUniqueParams: true

# Description: boolean, toggles whether unicode identifiers are allowed in names or not, default is false
allowUnicodeIdentifiers: false

# Description: Add form or body parameters to the beginning of the parameter list.
prependFormOrBodyParameters: false

# Description: Set to false for generators with better support for discriminators. (Python, Java, Go, PowerShell, C# have this enabled by default).
# Available Values:
#    true
#         The mapping in the discriminator includes descendent schemas that allOf inherit from self and the discriminator mapping schemas in the OAS document.
#    false
#         The mapping in the discriminator includes any descendent schemas that allOf inherit from self, any oneOf schemas, any anyOf schemas, any x-discriminator-values, and the discriminator mapping schemas in the OAS document AND Codegen validates that oneOf and anyOf schemas contain the required discriminator and throws an error if the discriminator is missing.
legacyDiscriminatorBehavior: true

# Description: If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
# Available Values:
#    false
#         The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
#    true
#         Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
disallowAdditionalPropertiesIfNotPresent: true

# Description: If the server adds new enum cases, that are unknown by an old spec/client, the client will fail to parse the network response.With this option enabled, each enum will have a new case, 'unknown_default_open_api', so that when the server sends an enum case that is not known by the client/spec, they can safely fallback to this case.
# Available Values:
#    false
#         No changes to the enum's are made, this is the default option.
#    true
#         With this option enabled, each enum will have a new case, 'unknown_default_open_api', so that when the enum case sent by the server is not known by the client/spec, can safely be decoded to this case.
enumUnknownDefaultCase: false

# Description: package for generated models
modelPackage: ai.lamin.lamin-api-client.model # Default: org.openapitools.client.model

# Description: package for generated api classes
apiPackage: ai.lamin.lamin-api-client.api # Default: org.openapitools.client.api

# Description: root package for generated code
invokerPackage: ai.lamin.lamin-api-client # Default: org.openapitools.client

# Description: groupId in generated pom.xml
groupId: ai.lamin # Default: org.openapitools

# Description: artifactId in generated pom.xml. This also becomes part of the generated library's filename
artifactId: lamin-api-client

# Description: artifact version in generated pom.xml. This also becomes part of the generated library's filename. If not provided, uses the version from the OpenAPI specification file. If that's also not present, uses the default value of the artifactVersion option.
artifactVersion: 0.0.2

# Description: artifact URL in generated pom.xml
artifactUrl: https://github.com/laminlabs/lamin-api-client-java

# Description: artifact description in generated pom.xml
artifactDescription: Java client for the Lamin API # Default: OpenAPI Java

# Description: SCM connection in generated pom.xml
scmConnection: scm:git:git@github.com:laminlabs/lamin-api-client-java.git # Default: scm:git:git@github.com:openapitools/openapi-generator.git

# Description: SCM developer connection in generated pom.xml
scmDeveloperConnection: scm:git:git@github.com:laminlabs/lamin-api-client-java.git # Default: scm:git:git@github.com:openapitools/openapi-generator.git

# Description: SCM URL in generated pom.xml
scmUrl: https://github.com/laminlabs/lamin-api-client-java # Default: https://github.com/openapitools/openapi-generator

# Description: developer name in generated pom.xml
developerName: Lamin Labs # Default: OpenAPI-Generator Contributors

# Description: developer email in generated pom.xml
developerEmail: open-source@lamin.ai # Default: team@openapitools.org

# Description: developer organization in generated pom.xml
developerOrganization: Lamin Labs # Default: OpenAPITools.org

# Description: developer organization URL in generated pom.xml
developerOrganizationUrl: https://lamin.ai/ # Default: http://openapitools.org

# Description: The name of the license
licenseName: Apache 2.0 # Default: Unlicense

# Description: The URL of the license
licenseUrl: https://opensource.org/licenses/Apache-2.0 # Default: http://unlicense.org

# Description: source folder for generated code
sourceFolder: src/main/java

# Description: boolean - toggle "implements Serializable" for generated models
serializableModel: false

# Description: Treat BigDecimal values as Strings to avoid precision loss.
bigDecimalAsString: false

# Description: Whether the discriminator value lookup should be case-sensitive or not. This option only works for Java API client
discriminatorCaseSensitive: true

# Description: Hides the generation timestamp when files are generated.
hideGenerationTimestamp: false

# Description: whether to include support for application/xml content type and include XML annotations in the model (works with libraries that provide support for JSON and XML)
withXml: false

# Description: whether to use a java interface to describe a set of oneOf options, where each option is a class that implements the interface
useOneOfInterfaces: false

# Description: Option. Date library to use
# Available Values:
#    joda
#         Joda (for legacy app only)
#    legacy
#         Legacy java.util.Date
#    java8-localdatetime
#         Java 8 using LocalDateTime (for legacy app only)
#    java8
#         Java 8 native JSR310 (preferred for jdk 1.8+)
dateLibrary: java8

# Description: Disable HTML escaping of JSON strings when using gson (needed to avoid problems with byte[] fields)
disableHtmlEscaping: false

# Description: Set booleanGetterPrefix
booleanGetterPrefix: get

# Description: Ignore anyOf keyword in enum
ignoreAnyOfInEnum: false

# Description: Additional annotations for enum type(class level annotations)
# additionalEnumTypeAnnotations:

# Description: Additional annotations for model type(class level annotations). List separated by semicolon(;) or new line (Linux or Windows)
# additionalModelTypeAnnotations:

# Description: Additional annotations for oneOf interfaces(class level annotations). List separated by semicolon(;) or new line (Linux or Windows)
# additionalOneOfTypeAnnotations:

# Description: Enable OpenAPI Jackson Nullable library. Not supported by `microprofile` library.
openApiNullable: true

# Description: Skip header parameters in the generated API methods using @ApiImplicitParams annotation.
implicitHeaders: false

# Description: Skip header parameters that matches given regex in the generated API methods using @ApiImplicitParams annotation. Note: this parameter is ignored when implicitHeaders=true
# implicitHeadersRegex:

# Description: Fix camelCase when starting with $ sign. when true : $Value when false : $value
camelCaseDollarSign: false

# Description: whether to use Jakarta EE namespace instead of javax
useJakartaEe: false

# Description: Set containers (array, set, map) default to null
containerDefaultToNull: false

# Description: whether to generate a constructor for all arguments
generateConstructorWithAllArgs: false

# Description: Whether to generate builders for models
generateBuilders: false

# Description: parent groupId in generated pom N.B. parentGroupId, parentArtifactId and parentVersion must all be specified for any of them to take effect
# parentGroupId:

# Description: parent artifactId in generated pom N.B. parentGroupId, parentArtifactId and parentVersion must all be specified for any of them to take effect
# parentArtifactId:

# Description: parent version in generated pom N.B. parentGroupId, parentArtifactId and parentVersion must all be specified for any of them to take effect
# parentVersion:

# Description: Uses a SNAPSHOT version.
# Available Values:
#    true
#         Use a SnapShot Version
#    false
#         Use a Release Version
# snapshotVersion:

# Description: Set output folder for models and APIs tests
testOutput: src/test # Default ${project.build.directory}/generated-test-sources/openapi

# Description: Select the OpenAPI documentation provider.
# Available Values:
#    none
#         Do not publish an OpenAPI specification.
#    source
#         Publish the original input OpenAPI specification.
documentationProvider: source

# Description: Select the complementary documentation annotation library.
# Available Values:
#    none
#         Do not annotate Model and Api with complementary annotations.
#    swagger1
#         Annotate Model and Api using the Swagger Annotations 1.x library.
#    swagger2
#         Annotate Model and Api using the Swagger Annotations 2.x library.
annotationLibrary: none

# Description: Naming convention for enum properties: 'MACRO_CASE' and 'legacy'
enumPropertyNaming: MACRO_CASE

# Description: Whether to use the RxJava2 adapter with the retrofit2 library. IMPORTANT: This option has been deprecated.
useRxJava2: false

# Description: Whether to use the RxJava3 adapter with the retrofit2 library. IMPORTANT: This option has been deprecated.
useRxJava3: false

# Description: Whether to generate models for Android that implement Parcelable with the okhttp-gson library.
parcelableModel: false

# Description: Use Play! Async HTTP client (Play WS API)
usePlayWS: false

# Description: Use BeanValidation API annotations
useBeanValidation: false

# Description: Perform BeanValidation
performBeanValidation: false

# Description: Send gzip-encoded requests
useGzipFeature: false

# Description: Use RuntimeException instead of Exception. Only jersey2, jersey3, okhttp-gson, vertx, microprofile support this option.
useRuntimeException: false

# Description: If true, async handlers will be used, instead of the sync version
asyncNative: false

# Description: Use org.apache.commons.lang3.builder for equals and hashCode in the models. WARNING: This will fail under a security manager, unless the appropriate permissions are set up correctly and also there's potential performance impact.
useReflectionEqualsHashCode: false

# Description: Make API response's headers case-insensitive. Available on okhttp-gson, jersey2 libraries
caseInsensitiveResponseHeaders: false

# Description: Framework for microprofile. Possible values "kumuluzee"
# microprofileFramework:

# Description: Whether to use async types for microprofile (currently only Smallrye Mutiny is supported).
# microprofileMutiny:

# Description: Use alternative types instead of java.io.File to allow passing bytes without a file on disk. Available on resttemplate, webclient, restclient, libraries
useAbstractionForFiles: false

# Description: Generate operations dynamically at runtime from an OAS
dynamicOperations: false

# Description: Support streaming endpoint (beta)
supportStreaming: false

# Description: whether to include AWS v4 signature support (only available for okhttp-gson library)
withAWSV4Signature: false

# Description: Append additional Gradle properties to the gradle.properties file
# gradleProperties:

# Description: Error Object type. (This option is for okhttp-gson only)
# errorObjectType:

# Description: Config key in @RegisterRestClient. Default to none. Only `microprofile` supports this option.
# configKey:

# Description: If true, set tag as key in @RegisterRestClient. Default to false. Only `microprofile` supports this option.
# configKeyFromClassName:

# Description: Use the discriminator's mapping in oneOf to speed up the model lookup. IMPORTANT: Validation (e.g. one and only one match in oneOf's schemas) will be skipped. Only jersey2, jersey3, native, okhttp-gson support this option.
useOneOfDiscriminatorLookup: false

# Description: Version of MicroProfile Rest Client API.
# microprofileRestClientVersion:

# Description: Setting this property to "true" will generate functions with a single argument containing all API endpoint parameters instead of one argument per parameter. ONLY jersey2, jersey3, okhttp-gson, microprofile, Spring RestClient, Spring WebClient support this option. Setting this property to "static" does the same as "true", but also makes the generated arguments class static with single parameter instantiation.
useSingleRequestParameter: false

# Description: Making all WebClient operations blocking(sync). Note that if on operation 'x-webclient-blocking: false' then such operation won't be sync
webclientBlockingOperations: false

# Description: For resttemplate, configure whether to create `ApiClient.java` and Apis clients as bean (with `@Component` annotation).
generateClientAsBean: false

# Description: Generate toUrlQueryString in POJO (default to true). Available on `native`, `apache-httpclient` libraries.
supportUrlQuery: false

# Description: Use `equalsIgnoreCase` when String for enum comparison
useEnumCaseInsensitive: false

# Description: Fail Jackson de-serialization on unknown properties
failOnUnknownProperties: false

# Description: library template (sub-template) to use
# Available Values:
#    jersey2
#         HTTP client: Jersey client 2.25.1. JSON processing: Jackson 2.17.1
#    jersey3
#         HTTP client: Jersey client 3.1.1. JSON processing: Jackson 2.17.1
#    feign
#         HTTP client: OpenFeign 13.2.1. JSON processing: Jackson 2.17.1 or Gson 2.10.1
#    okhttp-gson
#         [DEFAULT] HTTP client: OkHttp 4.11.0. JSON processing: Gson 2.10.1. Enable Parcelable models on Android using '-DparcelableModel=true'. Enable gzip request encoding using '-DuseGzipFeature=true'.
#    retrofit2
#         HTTP client: OkHttp 4.11.0. JSON processing: Gson 2.10.1 (Retrofit 2.5.0) or Jackson 2.17.1. Enable the RxJava adapter using '-DuseRxJava[2/3]=true'. (RxJava 1.x or 2.x or 3.x)
#    resttemplate
#         HTTP client: Spring RestTemplate 5.3.33 (6.1.5 if `useJakartaEe=true`). JSON processing: Jackson 2.17.1
#    webclient
#         HTTP client: Spring WebClient 5.1.18. JSON processing: Jackson 2.17.1
#    restclient
#         HTTP client: Spring RestClient 6.1.6. JSON processing: Jackson 2.17.1
#    resteasy
#         HTTP client: Resteasy client 4.7.6. JSON processing: Jackson 2.17.1
#    vertx
#         HTTP client: VertX client 3.5.2. JSON processing: Jackson 2.17.1
#    google-api-client
#         HTTP client: Google API client 2.2.0. JSON processing: Jackson 2.17.1
#    rest-assured
#         HTTP client: rest-assured 5.3.2. JSON processing: Gson 2.10.1 or Jackson 2.17.1. Only for Java 8
#    native
#         HTTP client: Java native HttpClient. JSON processing: Jackson 2.17.1. Only for Java11+
#    microprofile
#         HTTP client: Microprofile client 2.0 (default, set desired version via `microprofileRestClientVersion=x.x.x`). JSON processing: JSON-B 1.0.2 or Jackson 2.17.1
#    apache-httpclient
#         HTTP client: Apache httpclient 5.2.1. JSON processing: Jackson 2.17.1
library: okhttp-gson

# Description: Serialization library, default depends on value of the option library
# Available Values:
#    jsonb
#         Use JSON-B as serialization library
#    jackson
#         Use Jackson as serialization library
#    gson
#         Use Gson as serialization library
# serializationLibrary:
