/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client_java.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AttachSpaceToRecordRequestBody
 */
public class AttachSpaceToRecordRequestBodyTest {
    private final AttachSpaceToRecordRequestBody model = new AttachSpaceToRecordRequestBody();

    /**
     * Model tests for AttachSpaceToRecordRequestBody
     */
    @Test
    public void testAttachSpaceToRecordRequestBody() {
        // TODO: test AttachSpaceToRecordRequestBody
    }

    /**
     * Test the property 'moduleName'
     */
    @Test
    public void moduleNameTest() {
        // TODO: test moduleName
    }

    /**
     * Test the property 'modelName'
     */
    @Test
    public void modelNameTest() {
        // TODO: test modelName
    }

    /**
     * Test the property 'recordId'
     */
    @Test
    public void recordIdTest() {
        // TODO: test recordId
    }

}
