/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiCallback;
import ai.lamin.lamin_api_client.ApiClient;
import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.ApiResponse;
import ai.lamin.lamin_api_client.Configuration;
import ai.lamin.lamin_api_client.Pair;
import ai.lamin.lamin_api_client.ProgressRequestBody;
import ai.lamin.lamin_api_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.lamin.lamin_api_client.model.GetRecordsRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InstanceFeaturesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InstanceFeaturesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InstanceFeaturesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost
     * @param moduleName  (required)
     * @param modelName  (required)
     * @param instanceId  (required)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @param authorization  (optional)
     * @param getRecordsRequestBody  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostCall(String moduleName, String modelName, UUID instanceId, Integer limit, Integer offset, String authorization, GetRecordsRequestBody getRecordsRequestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = getRecordsRequestBody;

        // create path and map variables
        String localVarPath = "/instances/{instance_id}/modules/{module_name}/{model_name}/query_features"
            .replace("{" + "module_name" + "}", localVarApiClient.escapeString(moduleName.toString()))
            .replace("{" + "model_name" + "}", localVarApiClient.escapeString(modelName.toString()))
            .replace("{" + "instance_id" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostValidateBeforeCall(String moduleName, String modelName, UUID instanceId, Integer limit, Integer offset, String authorization, GetRecordsRequestBody getRecordsRequestBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'moduleName' is set
        if (moduleName == null) {
            throw new ApiException("Missing the required parameter 'moduleName' when calling queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost(Async)");
        }

        // verify the required parameter 'modelName' is set
        if (modelName == null) {
            throw new ApiException("Missing the required parameter 'modelName' when calling queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost(Async)");
        }

        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost(Async)");
        }

        return queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostCall(moduleName, modelName, instanceId, limit, offset, authorization, getRecordsRequestBody, _callback);

    }

    /**
     * Query Linked Features
     * Queries and returns a flat list of all unique Feature records associated with a set of filtered primary model records.
     * @param moduleName  (required)
     * @param modelName  (required)
     * @param instanceId  (required)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @param authorization  (optional)
     * @param getRecordsRequestBody  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost(String moduleName, String modelName, UUID instanceId, Integer limit, Integer offset, String authorization, GetRecordsRequestBody getRecordsRequestBody) throws ApiException {
        ApiResponse<Object> localVarResp = queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostWithHttpInfo(moduleName, modelName, instanceId, limit, offset, authorization, getRecordsRequestBody);
        return localVarResp.getData();
    }

    /**
     * Query Linked Features
     * Queries and returns a flat list of all unique Feature records associated with a set of filtered primary model records.
     * @param moduleName  (required)
     * @param modelName  (required)
     * @param instanceId  (required)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @param authorization  (optional)
     * @param getRecordsRequestBody  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostWithHttpInfo(String moduleName, String modelName, UUID instanceId, Integer limit, Integer offset, String authorization, GetRecordsRequestBody getRecordsRequestBody) throws ApiException {
        okhttp3.Call localVarCall = queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostValidateBeforeCall(moduleName, modelName, instanceId, limit, offset, authorization, getRecordsRequestBody, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query Linked Features (asynchronously)
     * Queries and returns a flat list of all unique Feature records associated with a set of filtered primary model records.
     * @param moduleName  (required)
     * @param modelName  (required)
     * @param instanceId  (required)
     * @param limit  (optional, default to 50)
     * @param offset  (optional, default to 0)
     * @param authorization  (optional)
     * @param getRecordsRequestBody  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostAsync(String moduleName, String modelName, UUID instanceId, Integer limit, Integer offset, String authorization, GetRecordsRequestBody getRecordsRequestBody, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostValidateBeforeCall(moduleName, modelName, instanceId, limit, offset, authorization, getRecordsRequestBody, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
