/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiCallback;
import ai.lamin.lamin_api_client.ApiClient;
import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.ApiResponse;
import ai.lamin.lamin_api_client.Configuration;
import ai.lamin.lamin_api_client.Pair;
import ai.lamin.lamin_api_client.ProgressRequestBody;
import ai.lamin.lamin_api_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.lamin.lamin_api_client.model.CreateArtifactRequestBody;
import java.io.File;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InstanceArtifactsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InstanceArtifactsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InstanceArtifactsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createArtifactInstancesInstanceIdArtifactsCreatePost
     * @param instanceId Instance UUID. (required)
     * @param createArtifactRequestBody  (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createArtifactInstancesInstanceIdArtifactsCreatePostCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull CreateArtifactRequestBody createArtifactRequestBody, @javax.annotation.Nullable UUID spaceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createArtifactRequestBody;

        // create path and map variables
        String localVarPath = "/instances/{instance_id}/artifacts/create"
            .replace("{" + "instance_id" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (spaceId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("space_id", spaceId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "LaminAccessToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createArtifactInstancesInstanceIdArtifactsCreatePostValidateBeforeCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull CreateArtifactRequestBody createArtifactRequestBody, @javax.annotation.Nullable UUID spaceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling createArtifactInstancesInstanceIdArtifactsCreatePost(Async)");
        }

        // verify the required parameter 'createArtifactRequestBody' is set
        if (createArtifactRequestBody == null) {
            throw new ApiException("Missing the required parameter 'createArtifactRequestBody' when calling createArtifactInstancesInstanceIdArtifactsCreatePost(Async)");
        }

        return createArtifactInstancesInstanceIdArtifactsCreatePostCall(instanceId, createArtifactRequestBody, spaceId, _callback);

    }

    /**
     * Create Artifact
     * Create an artifact from an existing storage path.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param createArtifactRequestBody  (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object createArtifactInstancesInstanceIdArtifactsCreatePost(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull CreateArtifactRequestBody createArtifactRequestBody, @javax.annotation.Nullable UUID spaceId) throws ApiException {
        ApiResponse<Object> localVarResp = createArtifactInstancesInstanceIdArtifactsCreatePostWithHttpInfo(instanceId, createArtifactRequestBody, spaceId);
        return localVarResp.getData();
    }

    /**
     * Create Artifact
     * Create an artifact from an existing storage path.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param createArtifactRequestBody  (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> createArtifactInstancesInstanceIdArtifactsCreatePostWithHttpInfo(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull CreateArtifactRequestBody createArtifactRequestBody, @javax.annotation.Nullable UUID spaceId) throws ApiException {
        okhttp3.Call localVarCall = createArtifactInstancesInstanceIdArtifactsCreatePostValidateBeforeCall(instanceId, createArtifactRequestBody, spaceId, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Artifact (asynchronously)
     * Create an artifact from an existing storage path.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param createArtifactRequestBody  (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createArtifactInstancesInstanceIdArtifactsCreatePostAsync(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull CreateArtifactRequestBody createArtifactRequestBody, @javax.annotation.Nullable UUID spaceId, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = createArtifactInstancesInstanceIdArtifactsCreatePostValidateBeforeCall(instanceId, createArtifactRequestBody, spaceId, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getArtifactByPathInstancesInstanceIdArtifactsByPathGet
     * @param instanceId Instance UUID. (required)
     * @param path Artifact storage path. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getArtifactByPathInstancesInstanceIdArtifactsByPathGetCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull String path, @javax.annotation.Nullable UUID spaceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/instances/{instance_id}/artifacts/by-path"
            .replace("{" + "instance_id" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (path != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("path", path));
        }

        if (spaceId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("space_id", spaceId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "LaminAccessToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getArtifactByPathInstancesInstanceIdArtifactsByPathGetValidateBeforeCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull String path, @javax.annotation.Nullable UUID spaceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling getArtifactByPathInstancesInstanceIdArtifactsByPathGet(Async)");
        }

        // verify the required parameter 'path' is set
        if (path == null) {
            throw new ApiException("Missing the required parameter 'path' when calling getArtifactByPathInstancesInstanceIdArtifactsByPathGet(Async)");
        }

        return getArtifactByPathInstancesInstanceIdArtifactsByPathGetCall(instanceId, path, spaceId, _callback);

    }

    /**
     * Get Artifact By Path
     * Return artifact metadata for a storage path.  **Permissions:** Requires read access to the instance.
     * @param instanceId Instance UUID. (required)
     * @param path Artifact storage path. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object getArtifactByPathInstancesInstanceIdArtifactsByPathGet(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull String path, @javax.annotation.Nullable UUID spaceId) throws ApiException {
        ApiResponse<Object> localVarResp = getArtifactByPathInstancesInstanceIdArtifactsByPathGetWithHttpInfo(instanceId, path, spaceId);
        return localVarResp.getData();
    }

    /**
     * Get Artifact By Path
     * Return artifact metadata for a storage path.  **Permissions:** Requires read access to the instance.
     * @param instanceId Instance UUID. (required)
     * @param path Artifact storage path. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getArtifactByPathInstancesInstanceIdArtifactsByPathGetWithHttpInfo(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull String path, @javax.annotation.Nullable UUID spaceId) throws ApiException {
        okhttp3.Call localVarCall = getArtifactByPathInstancesInstanceIdArtifactsByPathGetValidateBeforeCall(instanceId, path, spaceId, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Artifact By Path (asynchronously)
     * Return artifact metadata for a storage path.  **Permissions:** Requires read access to the instance.
     * @param instanceId Instance UUID. (required)
     * @param path Artifact storage path. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getArtifactByPathInstancesInstanceIdArtifactsByPathGetAsync(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull String path, @javax.annotation.Nullable UUID spaceId, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getArtifactByPathInstancesInstanceIdArtifactsByPathGetValidateBeforeCall(instanceId, path, spaceId, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for uploadArtifactInstancesInstanceIdArtifactsUploadPost
     * @param instanceId Instance UUID. (required)
     * @param _file Artifact file to upload. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param kwargs JSON object string with additional upload arguments. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadArtifactInstancesInstanceIdArtifactsUploadPostCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable UUID spaceId, @javax.annotation.Nullable String kwargs, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/instances/{instance_id}/artifacts/upload"
            .replace("{" + "instance_id" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        if (kwargs != null) {
            localVarFormParams.put("kwargs", kwargs);
        }

        if (spaceId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("space_id", spaceId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "LaminAccessToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadArtifactInstancesInstanceIdArtifactsUploadPostValidateBeforeCall(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable UUID spaceId, @javax.annotation.Nullable String kwargs, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling uploadArtifactInstancesInstanceIdArtifactsUploadPost(Async)");
        }

        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling uploadArtifactInstancesInstanceIdArtifactsUploadPost(Async)");
        }

        return uploadArtifactInstancesInstanceIdArtifactsUploadPostCall(instanceId, _file, spaceId, kwargs, _callback);

    }

    /**
     * Upload Artifact
     * Upload a file and register it as an artifact.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param _file Artifact file to upload. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param kwargs JSON object string with additional upload arguments. (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object uploadArtifactInstancesInstanceIdArtifactsUploadPost(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable UUID spaceId, @javax.annotation.Nullable String kwargs) throws ApiException {
        ApiResponse<Object> localVarResp = uploadArtifactInstancesInstanceIdArtifactsUploadPostWithHttpInfo(instanceId, _file, spaceId, kwargs);
        return localVarResp.getData();
    }

    /**
     * Upload Artifact
     * Upload a file and register it as an artifact.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param _file Artifact file to upload. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param kwargs JSON object string with additional upload arguments. (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> uploadArtifactInstancesInstanceIdArtifactsUploadPostWithHttpInfo(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable UUID spaceId, @javax.annotation.Nullable String kwargs) throws ApiException {
        okhttp3.Call localVarCall = uploadArtifactInstancesInstanceIdArtifactsUploadPostValidateBeforeCall(instanceId, _file, spaceId, kwargs, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Upload Artifact (asynchronously)
     * Upload a file and register it as an artifact.  **Permissions:** Requires write access to the target instance or space.
     * @param instanceId Instance UUID. (required)
     * @param _file Artifact file to upload. (required)
     * @param spaceId Space UUID for space-scoped access checks. (optional)
     * @param kwargs JSON object string with additional upload arguments. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadArtifactInstancesInstanceIdArtifactsUploadPostAsync(@javax.annotation.Nonnull UUID instanceId, @javax.annotation.Nonnull File _file, @javax.annotation.Nullable UUID spaceId, @javax.annotation.Nullable String kwargs, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadArtifactInstancesInstanceIdArtifactsUploadPostValidateBeforeCall(instanceId, _file, spaceId, kwargs, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
