/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiCallback;
import ai.lamin.lamin_api_client.ApiClient;
import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.ApiResponse;
import ai.lamin.lamin_api_client.Configuration;
import ai.lamin.lamin_api_client.Pair;
import ai.lamin.lamin_api_client.ProgressRequestBody;
import ai.lamin.lamin_api_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.lamin.lamin_api_client.model.CreateServiceAccountApiKeyRequestBody;
import ai.lamin.lamin_api_client.model.CreateServiceAccountRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateServiceAccountRequestBody;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ServiceAccountsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ServiceAccountsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ServiceAccountsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost
     * @param organizationId  (required)
     * @param handle  (required)
     * @param createServiceAccountApiKeyRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createServiceAccountApiKeyRequestBody;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}/api-keys"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost(Async)");
        }

        // verify the required parameter 'createServiceAccountApiKeyRequestBody' is set
        if (createServiceAccountApiKeyRequestBody == null) {
            throw new ApiException("Missing the required parameter 'createServiceAccountApiKeyRequestBody' when calling createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost(Async)");
        }

        return createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostCall(organizationId, handle, createServiceAccountApiKeyRequestBody, authorization, _callback);

    }

    /**
     * Create Service Account Api Key
     * Create an API key for a service account.  The plaintext key is returned once only — store it immediately.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body   - **expires_at**: Expiry datetime for the API key   - **description**: Optional description  Returns: - **201**: API key created successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param createServiceAccountApiKeyRequestBody  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostWithHttpInfo(organizationId, handle, createServiceAccountApiKeyRequestBody, authorization);
        return localVarResp.getData();
    }

    /**
     * Create Service Account Api Key
     * Create an API key for a service account.  The plaintext key is returned once only — store it immediately.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body   - **expires_at**: Expiry datetime for the API key   - **description**: Optional description  Returns: - **201**: API key created successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param createServiceAccountApiKeyRequestBody  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostValidateBeforeCall(organizationId, handle, createServiceAccountApiKeyRequestBody, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Service Account Api Key (asynchronously)
     * Create an API key for a service account.  The plaintext key is returned once only — store it immediately.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body   - **expires_at**: Expiry datetime for the API key   - **description**: Optional description  Returns: - **201**: API key created successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param createServiceAccountApiKeyRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostValidateBeforeCall(organizationId, handle, createServiceAccountApiKeyRequestBody, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createServiceAccountServiceAccountsPut
     * @param createServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createServiceAccountServiceAccountsPutCall(@javax.annotation.Nonnull CreateServiceAccountRequestBody createServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createServiceAccountRequestBody;

        // create path and map variables
        String localVarPath = "/service-accounts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createServiceAccountServiceAccountsPutValidateBeforeCall(@javax.annotation.Nonnull CreateServiceAccountRequestBody createServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createServiceAccountRequestBody' is set
        if (createServiceAccountRequestBody == null) {
            throw new ApiException("Missing the required parameter 'createServiceAccountRequestBody' when calling createServiceAccountServiceAccountsPut(Async)");
        }

        return createServiceAccountServiceAccountsPutCall(createServiceAccountRequestBody, authorization, _callback);

    }

    /**
     * Create Service Account
     * Create a service account under an organization.  Parameters: - **body**: Request body containing service account details   - **handle**: Unique handle for the service account   - **organization_id**: UUID of the owning organization (caller must be admin/manager)   - **name**: Optional display name  Returns: - **201**: Service account created successfully
     * @param createServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object createServiceAccountServiceAccountsPut(@javax.annotation.Nonnull CreateServiceAccountRequestBody createServiceAccountRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = createServiceAccountServiceAccountsPutWithHttpInfo(createServiceAccountRequestBody, authorization);
        return localVarResp.getData();
    }

    /**
     * Create Service Account
     * Create a service account under an organization.  Parameters: - **body**: Request body containing service account details   - **handle**: Unique handle for the service account   - **organization_id**: UUID of the owning organization (caller must be admin/manager)   - **name**: Optional display name  Returns: - **201**: Service account created successfully
     * @param createServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> createServiceAccountServiceAccountsPutWithHttpInfo(@javax.annotation.Nonnull CreateServiceAccountRequestBody createServiceAccountRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createServiceAccountServiceAccountsPutValidateBeforeCall(createServiceAccountRequestBody, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Service Account (asynchronously)
     * Create a service account under an organization.  Parameters: - **body**: Request body containing service account details   - **handle**: Unique handle for the service account   - **organization_id**: UUID of the owning organization (caller must be admin/manager)   - **name**: Optional display name  Returns: - **201**: Service account created successfully
     * @param createServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createServiceAccountServiceAccountsPutAsync(@javax.annotation.Nonnull CreateServiceAccountRequestBody createServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = createServiceAccountServiceAccountsPutValidateBeforeCall(createServiceAccountRequestBody, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete
     * @param organizationId  (required)
     * @param handle  (required)
     * @param apiKeyId  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull Integer apiKeyId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}/api-keys/{api_key_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()))
            .replace("{" + "api_key_id" + "}", localVarApiClient.escapeString(apiKeyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull Integer apiKeyId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete(Async)");
        }

        // verify the required parameter 'apiKeyId' is set
        if (apiKeyId == null) {
            throw new ApiException("Missing the required parameter 'apiKeyId' when calling deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete(Async)");
        }

        return deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteCall(organizationId, handle, apiKeyId, authorization, _callback);

    }

    /**
     * Delete Service Account Api Key
     * Revoke an API key for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **api_key_id**: ID of the API key to revoke  Returns: - **200**: API key revoked successfully - **404**: API key not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param apiKeyId  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull Integer apiKeyId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteWithHttpInfo(organizationId, handle, apiKeyId, authorization);
        return localVarResp.getData();
    }

    /**
     * Delete Service Account Api Key
     * Revoke an API key for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **api_key_id**: ID of the API key to revoke  Returns: - **200**: API key revoked successfully - **404**: API key not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param apiKeyId  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull Integer apiKeyId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteValidateBeforeCall(organizationId, handle, apiKeyId, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Service Account Api Key (asynchronously)
     * Revoke an API key for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **api_key_id**: ID of the API key to revoke  Returns: - **200**: API key revoked successfully - **404**: API key not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param apiKeyId  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull Integer apiKeyId, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteValidateBeforeCall(organizationId, handle, apiKeyId, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteServiceAccountServiceAccountsOrganizationIdHandleDelete
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling deleteServiceAccountServiceAccountsOrganizationIdHandleDelete(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling deleteServiceAccountServiceAccountsOrganizationIdHandleDelete(Async)");
        }

        return deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteCall(organizationId, handle, authorization, _callback);

    }

    /**
     * Delete Service Account
     * Delete a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account deleted successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object deleteServiceAccountServiceAccountsOrganizationIdHandleDelete(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteWithHttpInfo(organizationId, handle, authorization);
        return localVarResp.getData();
    }

    /**
     * Delete Service Account
     * Delete a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account deleted successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteValidateBeforeCall(organizationId, handle, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Service Account (asynchronously)
     * Delete a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account deleted successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteValidateBeforeCall(organizationId, handle, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getServiceAccountServiceAccountsOrganizationIdHandleGet
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceAccountServiceAccountsOrganizationIdHandleGetCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getServiceAccountServiceAccountsOrganizationIdHandleGetValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling getServiceAccountServiceAccountsOrganizationIdHandleGet(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling getServiceAccountServiceAccountsOrganizationIdHandleGet(Async)");
        }

        return getServiceAccountServiceAccountsOrganizationIdHandleGetCall(organizationId, handle, authorization, _callback);

    }

    /**
     * Get Service Account
     * Get details of a specific service account by organization and handle.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account details retrieved successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object getServiceAccountServiceAccountsOrganizationIdHandleGet(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = getServiceAccountServiceAccountsOrganizationIdHandleGetWithHttpInfo(organizationId, handle, authorization);
        return localVarResp.getData();
    }

    /**
     * Get Service Account
     * Get details of a specific service account by organization and handle.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account details retrieved successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getServiceAccountServiceAccountsOrganizationIdHandleGetWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getServiceAccountServiceAccountsOrganizationIdHandleGetValidateBeforeCall(organizationId, handle, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Service Account (asynchronously)
     * Get details of a specific service account by organization and handle.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account details retrieved successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceAccountServiceAccountsOrganizationIdHandleGetAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getServiceAccountServiceAccountsOrganizationIdHandleGetValidateBeforeCall(organizationId, handle, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGet
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}/api-keys"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGet(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGet(Async)");
        }

        return listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetCall(organizationId, handle, authorization, _callback);

    }

    /**
     * List Service Account Api Keys
     * List API key metadata for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: API key list retrieved successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGet(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetWithHttpInfo(organizationId, handle, authorization);
        return localVarResp.getData();
    }

    /**
     * List Service Account Api Keys
     * List API key metadata for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: API key list retrieved successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetValidateBeforeCall(organizationId, handle, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Service Account Api Keys (asynchronously)
     * List API key metadata for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: API key list retrieved successfully
     * @param organizationId  (required)
     * @param handle  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetValidateBeforeCall(organizationId, handle, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGet
     * @param organizationId  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service-accounts/organizations/{organization_id}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGet(Async)");
        }

        return listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetCall(organizationId, authorization, _callback);

    }

    /**
     * List Service Accounts By Organization
     * List all service accounts for an organization.  Parameters: - **organization_id**: UUID of the organization  Returns: - **200**: List of service accounts retrieved successfully
     * @param organizationId  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGet(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetWithHttpInfo(organizationId, authorization);
        return localVarResp.getData();
    }

    /**
     * List Service Accounts By Organization
     * List all service accounts for an organization.  Parameters: - **organization_id**: UUID of the organization  Returns: - **200**: List of service accounts retrieved successfully
     * @param organizationId  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetValidateBeforeCall(organizationId, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Service Accounts By Organization (asynchronously)
     * List all service accounts for an organization.  Parameters: - **organization_id**: UUID of the organization  Returns: - **200**: List of service accounts retrieved successfully
     * @param organizationId  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetValidateBeforeCall(organizationId, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateServiceAccountServiceAccountsOrganizationIdHandlePatch
     * @param organizationId  (required)
     * @param handle  (required)
     * @param updateServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateServiceAccountServiceAccountsOrganizationIdHandlePatchCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull UpdateServiceAccountRequestBody updateServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateServiceAccountRequestBody;

        // create path and map variables
        String localVarPath = "/service-accounts/{organization_id}/{handle}"
            .replace("{" + "organization_id" + "}", localVarApiClient.escapeString(organizationId.toString()))
            .replace("{" + "handle" + "}", localVarApiClient.escapeString(handle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateServiceAccountServiceAccountsOrganizationIdHandlePatchValidateBeforeCall(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull UpdateServiceAccountRequestBody updateServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling updateServiceAccountServiceAccountsOrganizationIdHandlePatch(Async)");
        }

        // verify the required parameter 'handle' is set
        if (handle == null) {
            throw new ApiException("Missing the required parameter 'handle' when calling updateServiceAccountServiceAccountsOrganizationIdHandlePatch(Async)");
        }

        // verify the required parameter 'updateServiceAccountRequestBody' is set
        if (updateServiceAccountRequestBody == null) {
            throw new ApiException("Missing the required parameter 'updateServiceAccountRequestBody' when calling updateServiceAccountServiceAccountsOrganizationIdHandlePatch(Async)");
        }

        return updateServiceAccountServiceAccountsOrganizationIdHandlePatchCall(organizationId, handle, updateServiceAccountRequestBody, authorization, _callback);

    }

    /**
     * Update Service Account
     * Update a service account&#39;s details.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body containing updated details   - **name**: Optional new display name  Returns: - **200**: Service account updated successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param updateServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object updateServiceAccountServiceAccountsOrganizationIdHandlePatch(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull UpdateServiceAccountRequestBody updateServiceAccountRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = updateServiceAccountServiceAccountsOrganizationIdHandlePatchWithHttpInfo(organizationId, handle, updateServiceAccountRequestBody, authorization);
        return localVarResp.getData();
    }

    /**
     * Update Service Account
     * Update a service account&#39;s details.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body containing updated details   - **name**: Optional new display name  Returns: - **200**: Service account updated successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param updateServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> updateServiceAccountServiceAccountsOrganizationIdHandlePatchWithHttpInfo(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull UpdateServiceAccountRequestBody updateServiceAccountRequestBody, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = updateServiceAccountServiceAccountsOrganizationIdHandlePatchValidateBeforeCall(organizationId, handle, updateServiceAccountRequestBody, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Service Account (asynchronously)
     * Update a service account&#39;s details.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body containing updated details   - **name**: Optional new display name  Returns: - **200**: Service account updated successfully - **404**: Service account not found
     * @param organizationId  (required)
     * @param handle  (required)
     * @param updateServiceAccountRequestBody  (required)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateServiceAccountServiceAccountsOrganizationIdHandlePatchAsync(@javax.annotation.Nonnull UUID organizationId, @javax.annotation.Nonnull String handle, @javax.annotation.Nonnull UpdateServiceAccountRequestBody updateServiceAccountRequestBody, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateServiceAccountServiceAccountsOrganizationIdHandlePatchValidateBeforeCall(organizationId, handle, updateServiceAccountRequestBody, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
