/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Account
 */
public class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    public void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lnid'
     */
    @Test
    public void lnidTest() {
        // TODO: test lnid
    }

    /**
     * Test the property 'handle'
     */
    @Test
    public void handleTest() {
        // TODO: test handle
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'githubHandle'
     */
    @Test
    public void githubHandleTest() {
        // TODO: test githubHandle
    }

    /**
     * Test the property 'twitterHandle'
     */
    @Test
    public void twitterHandleTest() {
        // TODO: test twitterHandle
    }

    /**
     * Test the property 'linkedinHandle'
     */
    @Test
    public void linkedinHandleTest() {
        // TODO: test linkedinHandle
    }

    /**
     * Test the property 'avatarUrl'
     */
    @Test
    public void avatarUrlTest() {
        // TODO: test avatarUrl
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
