/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOrganizationRequestBody
 */
public class CreateOrganizationRequestBodyTest {
    private final CreateOrganizationRequestBody model = new CreateOrganizationRequestBody();

    /**
     * Model tests for CreateOrganizationRequestBody
     */
    @Test
    public void testCreateOrganizationRequestBody() {
        // TODO: test CreateOrganizationRequestBody
    }

    /**
     * Test the property 'handle'
     */
    @Test
    public void handleTest() {
        // TODO: test handle
    }

}
