/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExecuteFunctionRequestBody
 */
public class ExecuteFunctionRequestBodyTest {
    private final ExecuteFunctionRequestBody model = new ExecuteFunctionRequestBody();

    /**
     * Model tests for ExecuteFunctionRequestBody
     */
    @Test
    public void testExecuteFunctionRequestBody() {
        // TODO: test ExecuteFunctionRequestBody
    }

    /**
     * Test the property 'transformUid'
     */
    @Test
    public void transformUidTest() {
        // TODO: test transformUid
    }

    /**
     * Test the property 'functionName'
     */
    @Test
    public void functionNameTest() {
        // TODO: test functionName
    }

    /**
     * Test the property 'functionKwargs'
     */
    @Test
    public void functionKwargsTest() {
        // TODO: test functionKwargs
    }

}
