/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NonEmptyTablesResponse
 */
public class NonEmptyTablesResponseTest {
    private final NonEmptyTablesResponse model = new NonEmptyTablesResponse();

    /**
     * Model tests for NonEmptyTablesResponse
     */
    @Test
    public void testNonEmptyTablesResponse() {
        // TODO: test NonEmptyTablesResponse
    }

    /**
     * Test the property 'nonEmptyTables'
     */
    @Test
    public void nonEmptyTablesTest() {
        // TODO: test nonEmptyTables
    }

}
