/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.lamin.lamin_api_client.JSON;

/**
 * BatchUpdateBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-28T09:34:29.117144562+02:00[Europe/Brussels]", comments = "Generator version: 7.23.0")
public class BatchUpdateBody {
  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  @javax.annotation.Nonnull
  private List<Map<String, Object>> records = new ArrayList<>();

  public static final String SERIALIZED_NAME_INDEX_COLUMNS = "index_columns";
  @SerializedName(SERIALIZED_NAME_INDEX_COLUMNS)
  @javax.annotation.Nonnull
  private List<String> indexColumns = new ArrayList<>();

  public BatchUpdateBody() {
  }

  public BatchUpdateBody records(@javax.annotation.Nonnull List<Map<String, Object>> records) {
    this.records = records;
    return this;
  }

  public BatchUpdateBody addRecordsItem(Map<String, Object> recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Records to update. Each record must contain the key(s) in index_columns plus at least one mutable field.
   * @return records
   */
  @javax.annotation.Nonnull
  public List<Map<String, Object>> getRecords() {
    return records;
  }

  public void setRecords(@javax.annotation.Nonnull List<Map<String, Object>> records) {
    this.records = records;
  }


  public BatchUpdateBody indexColumns(@javax.annotation.Nonnull List<String> indexColumns) {
    this.indexColumns = indexColumns;
    return this;
  }

  public BatchUpdateBody addIndexColumnsItem(String indexColumnsItem) {
    if (this.indexColumns == null) {
      this.indexColumns = new ArrayList<>();
    }
    this.indexColumns.add(indexColumnsItem);
    return this;
  }

  /**
   * Column names that identify records to update, such as [&#39;uid&#39;].
   * @return indexColumns
   */
  @javax.annotation.Nonnull
  public List<String> getIndexColumns() {
    return indexColumns;
  }

  public void setIndexColumns(@javax.annotation.Nonnull List<String> indexColumns) {
    this.indexColumns = indexColumns;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpdateBody batchUpdateBody = (BatchUpdateBody) o;
    return Objects.equals(this.records, batchUpdateBody.records) &&
        Objects.equals(this.indexColumns, batchUpdateBody.indexColumns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, indexColumns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpdateBody {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    indexColumns: ").append(toIndentedString(indexColumns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("records", "index_columns"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("records", "index_columns"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchUpdateBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchUpdateBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchUpdateBody is not found in the empty JSON string", BatchUpdateBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchUpdateBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BatchUpdateBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchUpdateBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("records") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("records").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `records` to be an array in the JSON string but got `%s`", jsonObj.get("records").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("index_columns") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("index_columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `index_columns` to be an array in the JSON string but got `%s`", jsonObj.get("index_columns").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchUpdateBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchUpdateBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchUpdateBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchUpdateBody.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchUpdateBody>() {
           @Override
           public void write(JsonWriter out, BatchUpdateBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchUpdateBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchUpdateBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchUpdateBody
   * @throws IOException if the JSON string is invalid with respect to BatchUpdateBody
   */
  public static BatchUpdateBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchUpdateBody.class);
  }

  /**
   * Convert an instance of BatchUpdateBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

