/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.lamin.lamin_api_client.JSON;

/**
 * ExecuteFunctionRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-15T12:58:35.937124602+01:00[Europe/Brussels]", comments = "Generator version: 7.12.0")
public class ExecuteFunctionRequestBody {
  public static final String SERIALIZED_NAME_TRANSFORM_UID = "transform_uid";
  @SerializedName(SERIALIZED_NAME_TRANSFORM_UID)
  @javax.annotation.Nonnull
  private String transformUid;

  public static final String SERIALIZED_NAME_FUNCTION_NAME = "function_name";
  @SerializedName(SERIALIZED_NAME_FUNCTION_NAME)
  @javax.annotation.Nonnull
  private String functionName;

  public static final String SERIALIZED_NAME_FUNCTION_KWARGS = "function_kwargs";
  @SerializedName(SERIALIZED_NAME_FUNCTION_KWARGS)
  @javax.annotation.Nonnull
  private Map<String, Object> functionKwargs = new HashMap<>();

  public ExecuteFunctionRequestBody() {
  }

  public ExecuteFunctionRequestBody transformUid(@javax.annotation.Nonnull String transformUid) {
    this.transformUid = transformUid;
    return this;
  }

  /**
   * Get transformUid
   * @return transformUid
   */
  @javax.annotation.Nonnull
  public String getTransformUid() {
    return transformUid;
  }

  public void setTransformUid(@javax.annotation.Nonnull String transformUid) {
    this.transformUid = transformUid;
  }


  public ExecuteFunctionRequestBody functionName(@javax.annotation.Nonnull String functionName) {
    this.functionName = functionName;
    return this;
  }

  /**
   * Get functionName
   * @return functionName
   */
  @javax.annotation.Nonnull
  public String getFunctionName() {
    return functionName;
  }

  public void setFunctionName(@javax.annotation.Nonnull String functionName) {
    this.functionName = functionName;
  }


  public ExecuteFunctionRequestBody functionKwargs(@javax.annotation.Nonnull Map<String, Object> functionKwargs) {
    this.functionKwargs = functionKwargs;
    return this;
  }

  public ExecuteFunctionRequestBody putFunctionKwargsItem(String key, Object functionKwargsItem) {
    if (this.functionKwargs == null) {
      this.functionKwargs = new HashMap<>();
    }
    this.functionKwargs.put(key, functionKwargsItem);
    return this;
  }

  /**
   * Get functionKwargs
   * @return functionKwargs
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getFunctionKwargs() {
    return functionKwargs;
  }

  public void setFunctionKwargs(@javax.annotation.Nonnull Map<String, Object> functionKwargs) {
    this.functionKwargs = functionKwargs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteFunctionRequestBody executeFunctionRequestBody = (ExecuteFunctionRequestBody) o;
    return Objects.equals(this.transformUid, executeFunctionRequestBody.transformUid) &&
        Objects.equals(this.functionName, executeFunctionRequestBody.functionName) &&
        Objects.equals(this.functionKwargs, executeFunctionRequestBody.functionKwargs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transformUid, functionName, functionKwargs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteFunctionRequestBody {\n");
    sb.append("    transformUid: ").append(toIndentedString(transformUid)).append("\n");
    sb.append("    functionName: ").append(toIndentedString(functionName)).append("\n");
    sb.append("    functionKwargs: ").append(toIndentedString(functionKwargs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transform_uid");
    openapiFields.add("function_name");
    openapiFields.add("function_kwargs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("transform_uid");
    openapiRequiredFields.add("function_name");
    openapiRequiredFields.add("function_kwargs");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExecuteFunctionRequestBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExecuteFunctionRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExecuteFunctionRequestBody is not found in the empty JSON string", ExecuteFunctionRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExecuteFunctionRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExecuteFunctionRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExecuteFunctionRequestBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transform_uid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transform_uid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transform_uid").toString()));
      }
      if (!jsonObj.get("function_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `function_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("function_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExecuteFunctionRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExecuteFunctionRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExecuteFunctionRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExecuteFunctionRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ExecuteFunctionRequestBody>() {
           @Override
           public void write(JsonWriter out, ExecuteFunctionRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExecuteFunctionRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExecuteFunctionRequestBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExecuteFunctionRequestBody
   * @throws IOException if the JSON string is invalid with respect to ExecuteFunctionRequestBody
   */
  public static ExecuteFunctionRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExecuteFunctionRequestBody.class);
  }

  /**
   * Convert an instance of ExecuteFunctionRequestBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

