/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import java.util.Objects;
import ai.lamin.lamin_api_client.model.Dimension;
import ai.lamin.lamin_api_client.model.Measure;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.lamin.lamin_api_client.JSON;

/**
 * GroupByRequestBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-17T13:08:14.011869776+02:00[Europe/Brussels]", comments = "Generator version: 7.12.0")
public class GroupByRequestBody {
  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  @javax.annotation.Nonnull
  private List<Dimension> dimensions = new ArrayList<>();

  public static final String SERIALIZED_NAME_MEASURES = "measures";
  @SerializedName(SERIALIZED_NAME_MEASURES)
  @javax.annotation.Nonnull
  private List<Measure> measures = new ArrayList<>();

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  @javax.annotation.Nullable
  private Map<String, Object> filter;

  public GroupByRequestBody() {
  }

  public GroupByRequestBody dimensions(@javax.annotation.Nonnull List<Dimension> dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  public GroupByRequestBody addDimensionsItem(Dimension dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

  /**
   * Get dimensions
   * @return dimensions
   */
  @javax.annotation.Nonnull
  public List<Dimension> getDimensions() {
    return dimensions;
  }

  public void setDimensions(@javax.annotation.Nonnull List<Dimension> dimensions) {
    this.dimensions = dimensions;
  }


  public GroupByRequestBody measures(@javax.annotation.Nonnull List<Measure> measures) {
    this.measures = measures;
    return this;
  }

  public GroupByRequestBody addMeasuresItem(Measure measuresItem) {
    if (this.measures == null) {
      this.measures = new ArrayList<>();
    }
    this.measures.add(measuresItem);
    return this;
  }

  /**
   * Get measures
   * @return measures
   */
  @javax.annotation.Nonnull
  public List<Measure> getMeasures() {
    return measures;
  }

  public void setMeasures(@javax.annotation.Nonnull List<Measure> measures) {
    this.measures = measures;
  }


  public GroupByRequestBody filter(@javax.annotation.Nullable Map<String, Object> filter) {
    this.filter = filter;
    return this;
  }

  public GroupByRequestBody putFilterItem(String key, Object filterItem) {
    if (this.filter == null) {
      this.filter = new HashMap<>();
    }
    this.filter.put(key, filterItem);
    return this;
  }

  /**
   * Get filter
   * @return filter
   */
  @javax.annotation.Nullable
  public Map<String, Object> getFilter() {
    return filter;
  }

  public void setFilter(@javax.annotation.Nullable Map<String, Object> filter) {
    this.filter = filter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupByRequestBody groupByRequestBody = (GroupByRequestBody) o;
    return Objects.equals(this.dimensions, groupByRequestBody.dimensions) &&
        Objects.equals(this.measures, groupByRequestBody.measures) &&
        Objects.equals(this.filter, groupByRequestBody.filter);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions, measures, filter);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupByRequestBody {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    measures: ").append(toIndentedString(measures)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dimensions");
    openapiFields.add("measures");
    openapiFields.add("filter");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("dimensions");
    openapiRequiredFields.add("measures");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GroupByRequestBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GroupByRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupByRequestBody is not found in the empty JSON string", GroupByRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GroupByRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GroupByRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GroupByRequestBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("dimensions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `dimensions` to be an array in the JSON string but got `%s`", jsonObj.get("dimensions").toString()));
      }

      JsonArray jsonArraydimensions = jsonObj.getAsJsonArray("dimensions");
      // validate the required field `dimensions` (array)
      for (int i = 0; i < jsonArraydimensions.size(); i++) {
        Dimension.validateJsonElement(jsonArraydimensions.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("measures").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `measures` to be an array in the JSON string but got `%s`", jsonObj.get("measures").toString()));
      }

      JsonArray jsonArraymeasures = jsonObj.getAsJsonArray("measures");
      // validate the required field `measures` (array)
      for (int i = 0; i < jsonArraymeasures.size(); i++) {
        Measure.validateJsonElement(jsonArraymeasures.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupByRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupByRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupByRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupByRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupByRequestBody>() {
           @Override
           public void write(JsonWriter out, GroupByRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupByRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GroupByRequestBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GroupByRequestBody
   * @throws IOException if the JSON string is invalid with respect to GroupByRequestBody
   */
  public static GroupByRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupByRequestBody.class);
  }

  /**
   * Convert an instance of GroupByRequestBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

