/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.lamin.lamin_api_client.JSON;

/**
 * NonEmptyTablesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-12T11:16:27.287169544+01:00[Europe/Brussels]", comments = "Generator version: 7.12.0")
public class NonEmptyTablesResponse {
  public static final String SERIALIZED_NAME_NON_EMPTY_TABLES = "non_empty_tables";
  @SerializedName(SERIALIZED_NAME_NON_EMPTY_TABLES)
  @javax.annotation.Nonnull
  private Map<String, List<String>> nonEmptyTables = new HashMap<>();

  public NonEmptyTablesResponse() {
  }

  public NonEmptyTablesResponse nonEmptyTables(@javax.annotation.Nonnull Map<String, List<String>> nonEmptyTables) {
    this.nonEmptyTables = nonEmptyTables;
    return this;
  }

  public NonEmptyTablesResponse putNonEmptyTablesItem(String key, List<String> nonEmptyTablesItem) {
    if (this.nonEmptyTables == null) {
      this.nonEmptyTables = new HashMap<>();
    }
    this.nonEmptyTables.put(key, nonEmptyTablesItem);
    return this;
  }

  /**
   * A dictionary where keys are module names and values are lists of class names representing non-empty tables.
   * @return nonEmptyTables
   */
  @javax.annotation.Nonnull
  public Map<String, List<String>> getNonEmptyTables() {
    return nonEmptyTables;
  }

  public void setNonEmptyTables(@javax.annotation.Nonnull Map<String, List<String>> nonEmptyTables) {
    this.nonEmptyTables = nonEmptyTables;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NonEmptyTablesResponse nonEmptyTablesResponse = (NonEmptyTablesResponse) o;
    return Objects.equals(this.nonEmptyTables, nonEmptyTablesResponse.nonEmptyTables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonEmptyTables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NonEmptyTablesResponse {\n");
    sb.append("    nonEmptyTables: ").append(toIndentedString(nonEmptyTables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("non_empty_tables");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("non_empty_tables");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NonEmptyTablesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NonEmptyTablesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NonEmptyTablesResponse is not found in the empty JSON string", NonEmptyTablesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NonEmptyTablesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NonEmptyTablesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NonEmptyTablesResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NonEmptyTablesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NonEmptyTablesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NonEmptyTablesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NonEmptyTablesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<NonEmptyTablesResponse>() {
           @Override
           public void write(JsonWriter out, NonEmptyTablesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NonEmptyTablesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NonEmptyTablesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NonEmptyTablesResponse
   * @throws IOException if the JSON string is invalid with respect to NonEmptyTablesResponse
   */
  public static NonEmptyTablesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NonEmptyTablesResponse.class);
  }

  /**
   * Convert an instance of NonEmptyTablesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

