/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ORGANIZATION
 */
@JsonAdapter(ORGANIZATION.Adapter.class)
public enum ORGANIZATION {
  
  ADMIN("admin"),
  
  MANAGER("manager"),
  
  MEMBER("member"),
  
  GUEST("guest");

  private String value;

  ORGANIZATION(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ORGANIZATION fromValue(String value) {
    for (ORGANIZATION b : ORGANIZATION.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ORGANIZATION> {
    @Override
    public void write(final JsonWriter jsonWriter, final ORGANIZATION enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ORGANIZATION read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ORGANIZATION.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ORGANIZATION.fromValue(value);
  }
}

