/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.Account;
import ai.lamin.lamin_api_client.model.ApiKeyExchangeRequest;
import ai.lamin.lamin_api_client.model.ExternalJwtExchangeRequest;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    /**
     * Exchange API Key for Access Token
     *
     * Exchange a Lamin API key for an access token.  **Permissions:** Requires a valid Lamin API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exchangeApiKeyForAccessTokenTest() throws ApiException {
        ApiKeyExchangeRequest apiKeyExchangeRequest = null;
        Map<String, Object> response = api.exchangeApiKeyForAccessToken(apiKeyExchangeRequest);
        // TODO: test validations
    }

    /**
     * Exchange External JWT for Access Token
     *
     * Exchange an external IdP JWT for a Lamin access token.  The external token is verified against the app&#39;s JWKS and mapped to a Lamin account by email. The external token itself is the credential.  **Permissions:** Requires a valid JWT issued by the configured external app.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exchangeExternalJwtForAccessTokenTest() throws ApiException {
        ExternalJwtExchangeRequest externalJwtExchangeRequest = null;
        Map<String, Object> response = api.exchangeExternalJwtForAccessToken(externalJwtExchangeRequest);
        // TODO: test validations
    }

    /**
     * Get Caller Account
     *
     * Return the authenticated caller account when a token is provided.  **Permissions:** No authentication required. Unauthenticated requests return null.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCallerAccountAccountGetTest() throws ApiException {
        Account response = api.getCallerAccountAccountGet();
        // TODO: test validations
    }

}
