/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BackwardCompatibleEndpointsApi
 */
@Disabled
public class BackwardCompatibleEndpointsApiTest {

    private final BackwardCompatibleEndpointsApi api = new BackwardCompatibleEndpointsApi();

    /**
     * Get Db Token Backward Compatible
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDbTokenBackwardCompatibleAccessV2InstancesInstanceIdDbTokenGetTest() throws ApiException {
        UUID instanceId = null;
        String authorization = null;
        Object response = api.getDbTokenBackwardCompatibleAccessV2InstancesInstanceIdDbTokenGet(instanceId, authorization);
        // TODO: test validations
    }

}
