/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.DbTokenResponse;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceDbTokenApi
 */
@Disabled
public class InstanceDbTokenApiTest {

    private final InstanceDbTokenApi api = new InstanceDbTokenApi();

    /**
     * Get Db Token
     *
     * Return an access token for direct instance data access.  **Permissions:** Requires read access to the instance.  **Notes:** The token grants direct access to instance data.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDbTokenInstancesInstanceIdDbTokenGetTest() throws ApiException {
        UUID instanceId = null;
        UUID spaceId = null;
        DbTokenResponse response = api.getDbTokenInstancesInstanceIdDbTokenGet(instanceId, spaceId);
        // TODO: test validations
    }

}
