/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import ai.lamin.lamin_api_client.model.RegisterFormRequest;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceFormsApi
 */
@Disabled
public class InstanceFormsApiTest {

    private final InstanceFormsApi api = new InstanceFormsApi();

    /**
     * Register Form
     *
     * Register a form on the instance.  **Permissions:** Requires write access to the instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerFormInstancesInstanceIdFormsPostTest() throws ApiException {
        UUID instanceId = null;
        RegisterFormRequest registerFormRequest = null;
        UUID spaceId = null;
        Object response = api.registerFormInstancesInstanceIdFormsPost(instanceId, registerFormRequest, spaceId);
        // TODO: test validations
    }

}
