/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.GetRecordsRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceFeaturesApi
 */
@Disabled
public class InstanceFeaturesApiTest {

    private final InstanceFeaturesApi api = new InstanceFeaturesApi();

    /**
     * Query Linked Features
     *
     * Return features linked to matching primary records.  **Permissions:** Requires read access to the instance.  **Quota:** Returns at most 200 features per request.  **Notes:** Returns unique Feature records.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPostTest() throws ApiException {
        String moduleName = null;
        String modelName = null;
        UUID instanceId = null;
        Integer limit = null;
        Integer offset = null;
        UUID spaceId = null;
        GetRecordsRequestBody getRecordsRequestBody = null;
        Object response = api.queryLinkedFeaturesInstancesInstanceIdModulesModuleNameModelNameQueryFeaturesPost(moduleName, modelName, instanceId, limit, offset, spaceId, getRecordsRequestBody);
        // TODO: test validations
    }

}
