/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceFileExplorerApi
 */
@Disabled
public class InstanceFileExplorerApiTest {

    private final InstanceFileExplorerApi api = new InstanceFileExplorerApi();

    /**
     * Get Tree
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTreeInstancesInstanceIdFilesTreeGetTest() throws ApiException {
        UUID instanceId = null;
        String entityType = null;
        UUID spaceId = null;
        String authorization = null;
        Object response = api.getTreeInstancesInstanceIdFilesTreeGet(instanceId, entityType, spaceId, authorization);
        // TODO: test validations
    }

    /**
     * List Directory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDirectoryInstancesInstanceIdFilesEntityTypeGetTest() throws ApiException {
        String entityType = null;
        UUID instanceId = null;
        String path = null;
        UUID spaceId = null;
        String authorization = null;
        Object response = api.listDirectoryInstancesInstanceIdFilesEntityTypeGet(entityType, instanceId, path, spaceId, authorization);
        // TODO: test validations
    }

}
