/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.CreateArtifactRequestBody;
import java.io.File;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceArtifactsApi
 */
@Disabled
public class InstanceArtifactsApiTest {

    private final InstanceArtifactsApi api = new InstanceArtifactsApi();

    /**
     * Create Artifact
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createArtifactInstancesInstanceIdArtifactsCreatePostTest() throws ApiException {
        UUID instanceId = null;
        CreateArtifactRequestBody createArtifactRequestBody = null;
        String authorization = null;
        Object response = api.createArtifactInstancesInstanceIdArtifactsCreatePost(instanceId, createArtifactRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Upload Artifact
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadArtifactInstancesInstanceIdArtifactsUploadPostTest() throws ApiException {
        UUID instanceId = null;
        File _file = null;
        String authorization = null;
        String kwargs = null;
        Object response = api.uploadArtifactInstancesInstanceIdArtifactsUploadPost(instanceId, _file, authorization, kwargs);
        // TODO: test validations
    }

}
