/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceSchemaApi
 */
@Disabled
public class InstanceSchemaApiTest {

    private final InstanceSchemaApi api = new InstanceSchemaApi();

    /**
     * Get Relations
     *
     * Return related models for a schema model.  **Permissions:** Requires read access to the instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRelationsInstancesInstanceIdSchemaModuleNameModelNameGetTest() throws ApiException {
        String moduleName = null;
        String modelName = null;
        UUID instanceId = null;
        UUID spaceId = null;
        Object response = api.getRelationsInstancesInstanceIdSchemaModuleNameModelNameGet(moduleName, modelName, instanceId, spaceId);
        // TODO: test validations
    }

    /**
     * Get Schema
     *
     * Return the instance schema JSON.  **Permissions:** Requires read access to the instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSchemaInstancesInstanceIdSchemaGetTest() throws ApiException {
        UUID instanceId = null;
        UUID spaceId = null;
        Object response = api.getSchemaInstancesInstanceIdSchemaGet(instanceId, spaceId);
        // TODO: test validations
    }

}
