/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstanceLabelsApi
 */
@Disabled
public class InstanceLabelsApiTest {

    private final InstanceLabelsApi api = new InstanceLabelsApi();

    /**
     * Attach Label
     *
     * Attach a label to a record.  **Permissions:** Requires write access to the target instance or space.  **Notes:** Attaching an already-linked label succeeds.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void attachLabelInstancesInstanceIdModulesModuleNameModelNameIdLabelFieldLabelIdPutTest() throws ApiException {
        String moduleName = null;
        String modelName = null;
        Integer id = null;
        String labelField = null;
        Integer labelId = null;
        UUID instanceId = null;
        UUID spaceId = null;
        Object response = api.attachLabelInstancesInstanceIdModulesModuleNameModelNameIdLabelFieldLabelIdPut(moduleName, modelName, id, labelField, labelId, instanceId, spaceId);
        // TODO: test validations
    }

    /**
     * Detach Label
     *
     * Detach a label from a record.  **Permissions:** Requires write access to the target instance or space.  **Notes:** Removing a missing label link does not fail.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void detachLabelInstancesInstanceIdModulesModuleNameModelNameIdLabelFieldLabelIdDeleteTest() throws ApiException {
        String moduleName = null;
        String modelName = null;
        Integer id = null;
        String labelField = null;
        Integer labelId = null;
        UUID instanceId = null;
        UUID spaceId = null;
        Object response = api.detachLabelInstancesInstanceIdModulesModuleNameModelNameIdLabelFieldLabelIdDelete(moduleName, modelName, id, labelField, labelId, instanceId, spaceId);
        // TODO: test validations
    }

}
