/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.AddCollaboratorRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateCollaboratorRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstancesApi
 */
@Disabled
public class InstancesApiTest {

    private final InstancesApi api = new InstancesApi();

    /**
     * Add Collaborator
     *
     * Add a collaborator (account or team) to an instance.  Parameters: - **instance_id**: UUID of the instance to add the collaborator to (from URL path) - **body**: Request body containing collaborator details   - **account_id**: UUID of the account to add (mutually exclusive with team_id)   - **team_id**: UUID of the team to add (mutually exclusive with account_id)   - **role**: Role of the collaborator  Returns: - **201**: Collaborator added successfully - **400**: Invalid input (e.g., both account_id and team_id provided) - **409**: Collaborator was already added  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCollaboratorInstancesInstanceIdCollaboratorsPutTest() throws ApiException {
        UUID instanceId = null;
        AddCollaboratorRequestBody addCollaboratorRequestBody = null;
        String authorization = null;
        Object response = api.addCollaboratorInstancesInstanceIdCollaboratorsPut(instanceId, addCollaboratorRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Create Instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createInstanceInstancesPutTest() throws ApiException {
        String name = null;
        String storage = null;
        String schemaStr = null;
        String dbServerName = null;
        String storageUid = null;
        UUID accountId = null;
        UUID instanceId = null;
        String authorization = null;
        Map<String, Object> requestBody = null;
        Object response = api.createInstanceInstancesPut(name, storage, schemaStr, dbServerName, storageUid, accountId, instanceId, authorization, requestBody);
        // TODO: test validations
    }

    /**
     * Delete Instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInstanceInstancesInstanceIdDeleteTest() throws ApiException {
        UUID instanceId = null;
        String instanceName = null;
        String authorization = null;
        Object response = api.deleteInstanceInstancesInstanceIdDelete(instanceId, instanceName, authorization);
        // TODO: test validations
    }

    /**
     * List Collaborators
     *
     * List all collaborators of an instance.  Parameters: - **instance_id**: UUID of the instance to list collaborators for (from URL path)  Returns: - **200**: List of instance collaborators retrieved successfully  Requires read access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCollaboratorsInstancesInstanceIdCollaboratorsGetTest() throws ApiException {
        UUID instanceId = null;
        String authorization = null;
        Object response = api.listCollaboratorsInstancesInstanceIdCollaboratorsGet(instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Migrate Instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void migrateInstanceInstancesInstanceIdMigratePostTest() throws ApiException {
        UUID instanceId = null;
        String authorization = null;
        Object response = api.migrateInstanceInstancesInstanceIdMigratePost(instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Remove Collaborator
     *
     * Remove a collaborator from an instance.  Parameters: - **instance_id**: UUID of the instance (from URL path) - **account_id**: UUID of the account to remove (mutually exclusive with team_id) - **team_id**: UUID of the team to remove (mutually exclusive with account_id)  Returns: - **200**: Collaborator removed successfully - **400**: Invalid input (e.g., both account_id and team_id provided)  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCollaboratorInstancesInstanceIdCollaboratorsDeleteTest() throws ApiException {
        UUID instanceId = null;
        UUID accountId = null;
        UUID teamId = null;
        String authorization = null;
        Object response = api.removeCollaboratorInstancesInstanceIdCollaboratorsDelete(instanceId, accountId, teamId, authorization);
        // TODO: test validations
    }

    /**
     * Transfer Ownership
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferOwnershipInstancesInstanceIdOwnerHandlePatchTest() throws ApiException {
        String handle = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.transferOwnershipInstancesInstanceIdOwnerHandlePatch(handle, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Update Collaborator
     *
     * Update a collaborator&#39;s permissions on an instance.  Parameters: - **instance_id**: UUID of the instance (from URL path) - **body**: Request body containing collaborator details   - **account_id**: UUID of the account to update (mutually exclusive with team_id)   - **team_id**: UUID of the team to update (mutually exclusive with account_id)   - **role**: Role of the collaborator  Returns: - **200**: Collaborator updated successfully - **400**: Invalid input (e.g., both account_id and team_id provided)  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCollaboratorInstancesInstanceIdCollaboratorsPatchTest() throws ApiException {
        UUID instanceId = null;
        UpdateCollaboratorRequestBody updateCollaboratorRequestBody = null;
        String authorization = null;
        Object response = api.updateCollaboratorInstancesInstanceIdCollaboratorsPatch(instanceId, updateCollaboratorRequestBody, authorization);
        // TODO: test validations
    }

}
