/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.AddOrganizationMemberRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateOrganizationMemberRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationsApi
 */
@Disabled
public class OrganizationsApiTest {

    private final OrganizationsApi api = new OrganizationsApi();

    /**
     * Add Organization Member
     *
     * Add a member to an organization.  Parameters: - **organization_id**: UUID of the organization to add the member to - **account_id**: UUID of the account to add as a member - **body**: Request body containing member details   - **role**: Role of the member in the organization  Returns: - **201**: Organization member added successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addOrganizationMemberOrganizationsOrganizationIdMembersAccountIdPutTest() throws ApiException {
        UUID organizationId = null;
        UUID accountId = null;
        AddOrganizationMemberRequestBody addOrganizationMemberRequestBody = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.addOrganizationMemberOrganizationsOrganizationIdMembersAccountIdPut(organizationId, accountId, addOrganizationMemberRequestBody, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Get Organization
     *
     * Get details of a specific organization.  Parameters: - **organization_id**: UUID of the organization to retrieve  Returns: - **200**: Organization details retrieved successfully - **404**: Organization not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrganizationOrganizationsOrganizationIdGetTest() throws ApiException {
        UUID organizationId = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.getOrganizationOrganizationsOrganizationIdGet(organizationId, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * List Organization Members
     *
     * List all members of an organization.  Parameters: - **organization_id**: UUID of the organization to list members for  Returns: - **200**: List of organization members retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listOrganizationMembersOrganizationsOrganizationIdMembersGetTest() throws ApiException {
        UUID organizationId = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.listOrganizationMembersOrganizationsOrganizationIdMembersGet(organizationId, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Remove Organization Member
     *
     * Remove a member from an organization.  Parameters: - **organization_id**: UUID of the organization to remove the member from - **account_id**: UUID of the account to remove from the organization  Returns: - **200**: Organization member removed successfully - **404**: Member not found in organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeOrganizationMemberOrganizationsOrganizationIdMembersAccountIdDeleteTest() throws ApiException {
        UUID organizationId = null;
        UUID accountId = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.removeOrganizationMemberOrganizationsOrganizationIdMembersAccountIdDelete(organizationId, accountId, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Update Organization Member
     *
     * Update an organization member&#39;s details.  Parameters: - **organization_id**: UUID of the organization the member belongs to - **account_id**: UUID of the account to update - **body**: Request body containing updated member details   - **role**: Role of the member in the organization  Returns: - **200**: Organization member updated successfully - **404**: Member not found in organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateOrganizationMemberOrganizationsOrganizationIdMembersAccountIdPatchTest() throws ApiException {
        UUID organizationId = null;
        UUID accountId = null;
        UpdateOrganizationMemberRequestBody updateOrganizationMemberRequestBody = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.updateOrganizationMemberOrganizationsOrganizationIdMembersAccountIdPatch(organizationId, accountId, updateOrganizationMemberRequestBody, instanceId, authorization);
        // TODO: test validations
    }

}
