/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import ai.lamin.lamin_api_client.model.SetSecretRequestBody;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretsApi
 */
@Disabled
public class SecretsApiTest {

    private final SecretsApi api = new SecretsApi();

    /**
     * Delete Secret
     *
     * Delete a secret by name.  **Permissions:** Requires organization admin access.  **Notes:** Deletes the stored secret and its metadata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSecretSecretsOrganizationIdNameDeleteTest() throws ApiException {
        UUID organizationId = null;
        String name = null;
        Object response = api.deleteSecretSecretsOrganizationIdNameDelete(organizationId, name);
        // TODO: test validations
    }

    /**
     * Get Secret
     *
     * Return a secret value by name.  **Permissions:** Requires organization admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSecretSecretsOrganizationIdNameGetTest() throws ApiException {
        UUID organizationId = null;
        String name = null;
        Object response = api.getSecretSecretsOrganizationIdNameGet(organizationId, name);
        // TODO: test validations
    }

    /**
     * Set Secret
     *
     * Set a secret value by name.  **Permissions:** Requires organization admin access.  **Notes:** Creates the secret when it does not exist.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setSecretSecretsOrganizationIdNamePutTest() throws ApiException {
        UUID organizationId = null;
        String name = null;
        SetSecretRequestBody setSecretRequestBody = null;
        Object response = api.setSecretSecretsOrganizationIdNamePut(organizationId, name, setSecretRequestBody);
        // TODO: test validations
    }

}
