/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.CreateServiceAccountApiKeyRequestBody;
import ai.lamin.lamin_api_client.model.CreateServiceAccountRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateServiceAccountRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceAccountsApi
 */
@Disabled
public class ServiceAccountsApiTest {

    private final ServiceAccountsApi api = new ServiceAccountsApi();

    /**
     * Create Service Account Api Key
     *
     * Create an API key for a service account.  The plaintext key is returned once only — store it immediately.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body   - **expires_at**: Expiry datetime for the API key   - **description**: Optional description  Returns: - **201**: API key created successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPostTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        CreateServiceAccountApiKeyRequestBody createServiceAccountApiKeyRequestBody = null;
        String authorization = null;
        Object response = api.createServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysPost(organizationId, handle, createServiceAccountApiKeyRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Create Service Account
     *
     * Create a service account under an organization.  Parameters: - **body**: Request body containing service account details   - **handle**: Unique handle for the service account   - **organization_id**: UUID of the owning organization (caller must be admin/manager)   - **name**: Optional display name  Returns: - **201**: Service account created successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createServiceAccountServiceAccountsPutTest() throws ApiException {
        CreateServiceAccountRequestBody createServiceAccountRequestBody = null;
        String authorization = null;
        Object response = api.createServiceAccountServiceAccountsPut(createServiceAccountRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Delete Service Account Api Key
     *
     * Revoke an API key for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **api_key_id**: ID of the API key to revoke  Returns: - **200**: API key revoked successfully - **404**: API key not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDeleteTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        Integer apiKeyId = null;
        String authorization = null;
        Object response = api.deleteServiceAccountApiKeyServiceAccountsOrganizationIdHandleApiKeysApiKeyIdDelete(organizationId, handle, apiKeyId, authorization);
        // TODO: test validations
    }

    /**
     * Delete Service Account
     *
     * Delete a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account deleted successfully - **404**: Service account not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteServiceAccountServiceAccountsOrganizationIdHandleDeleteTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        String authorization = null;
        Object response = api.deleteServiceAccountServiceAccountsOrganizationIdHandleDelete(organizationId, handle, authorization);
        // TODO: test validations
    }

    /**
     * Get Service Account
     *
     * Get details of a specific service account by organization and handle.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: Service account details retrieved successfully - **404**: Service account not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceAccountServiceAccountsOrganizationIdHandleGetTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        String authorization = null;
        Object response = api.getServiceAccountServiceAccountsOrganizationIdHandleGet(organizationId, handle, authorization);
        // TODO: test validations
    }

    /**
     * List Service Account Api Keys
     *
     * List API key metadata for a service account.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account  Returns: - **200**: API key list retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGetTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        String authorization = null;
        Object response = api.listServiceAccountApiKeysServiceAccountsOrganizationIdHandleApiKeysGet(organizationId, handle, authorization);
        // TODO: test validations
    }

    /**
     * List Service Accounts By Organization
     *
     * List all service accounts for an organization.  Parameters: - **organization_id**: UUID of the organization  Returns: - **200**: List of service accounts retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGetTest() throws ApiException {
        UUID organizationId = null;
        String authorization = null;
        Object response = api.listServiceAccountsByOrganizationServiceAccountsOrganizationsOrganizationIdGet(organizationId, authorization);
        // TODO: test validations
    }

    /**
     * Update Service Account
     *
     * Update a service account&#39;s details.  Parameters: - **organization_id**: UUID of the owning organization - **handle**: Handle of the service account - **body**: Request body containing updated details   - **name**: Optional new display name  Returns: - **200**: Service account updated successfully - **404**: Service account not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateServiceAccountServiceAccountsOrganizationIdHandlePatchTest() throws ApiException {
        UUID organizationId = null;
        String handle = null;
        UpdateServiceAccountRequestBody updateServiceAccountRequestBody = null;
        String authorization = null;
        Object response = api.updateServiceAccountServiceAccountsOrganizationIdHandlePatch(organizationId, handle, updateServiceAccountRequestBody, authorization);
        // TODO: test validations
    }

}
