/*
 * LaminHub REST API
 * REST API for LaminHub.  Relevant documentation:  - [REST API](https://docs.lamin.ai/rest) - [Permissions](https://docs.lamin.ai/permissions) - [Spaces](https://docs.lamin.ai/lamindb.space) - [Storage](https://docs.lamin.ai/lamindb.storage) - [Records](https://docs.lamin.ai/records)
 *
 * The version of the OpenAPI document: 1.50.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.AddSpaceCollaboratorRequestBody;
import ai.lamin.lamin_api_client.model.AttachSpaceToRecordRequestBody;
import ai.lamin.lamin_api_client.model.CreateSpaceRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateSpaceCollaboratorRequestBody;
import ai.lamin.lamin_api_client.model.UpdateSpaceRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpacesApi
 */
@Disabled
public class SpacesApiTest {

    private final SpacesApi api = new SpacesApi();

    /**
     * Add Space Collaborator
     *
     * Add an account or team collaborator to a space.  **Permissions:** Adding a missing account as an organization guest requires organization manager or admin access.  **Notes:** Can add missing account collaborators as organization guests when requested.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSpaceCollaboratorSpacesSpaceIdCollaboratorsPutTest() throws ApiException {
        UUID spaceId = null;
        AddSpaceCollaboratorRequestBody addSpaceCollaboratorRequestBody = null;
        Object response = api.addSpaceCollaboratorSpacesSpaceIdCollaboratorsPut(spaceId, addSpaceCollaboratorRequestBody);
        // TODO: test validations
    }

    /**
     * Attach Space To Instance
     *
     * Attach a space to an instance.  **Permissions:** Requires instance admin access or organization manager or admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void attachSpaceToInstanceSpacesSpaceIdInstancesInstanceIdPutTest() throws ApiException {
        UUID spaceId = null;
        UUID instanceId = null;
        Object response = api.attachSpaceToInstanceSpacesSpaceIdInstancesInstanceIdPut(spaceId, instanceId);
        // TODO: test validations
    }

    /**
     * Create Space
     *
     * Create a space in an organization.  **Permissions:** Requires organization manager or admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSpaceSpacesPutTest() throws ApiException {
        CreateSpaceRequestBody createSpaceRequestBody = null;
        Object response = api.createSpaceSpacesPut(createSpaceRequestBody);
        // TODO: test validations
    }

    /**
     * Delete Space
     *
     * Delete a space.  **Permissions:** Requires organization manager or admin access.  **Notes:** The space must not be attached to any instances.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSpaceSpacesSpaceIdDeleteTest() throws ApiException {
        UUID spaceId = null;
        Object response = api.deleteSpaceSpacesSpaceIdDelete(spaceId);
        // TODO: test validations
    }

    /**
     * Detach Space From Instance
     *
     * Detach a space from an instance.  **Permissions:** Requires instance admin access or organization manager or admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void detachSpaceFromInstanceSpacesSpaceIdInstancesInstanceIdDeleteTest() throws ApiException {
        UUID spaceId = null;
        UUID instanceId = null;
        Object response = api.detachSpaceFromInstanceSpacesSpaceIdInstancesInstanceIdDelete(spaceId, instanceId);
        // TODO: test validations
    }

    /**
     * Get Space
     *
     * Return space details.  **Permissions:** Requires non-guest membership in the organization or space collaborator access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpaceSpacesSpaceIdGetTest() throws ApiException {
        UUID spaceId = null;
        Object response = api.getSpaceSpacesSpaceIdGet(spaceId);
        // TODO: test validations
    }

    /**
     * List Instance Spaces
     *
     * List spaces attached to an instance.  **Permissions:** Requires collaborator access to both the instance and returned spaces.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInstanceSpacesSpacesInstancesInstanceIdGetTest() throws ApiException {
        UUID instanceId = null;
        UUID spaceId = null;
        Object response = api.listInstanceSpacesSpacesInstancesInstanceIdGet(instanceId, spaceId);
        // TODO: test validations
    }

    /**
     * List Instances Using Space
     *
     * List instances that use a space.  **Permissions:** Requires collaborator access to both the space and returned instances.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInstancesUsingSpaceSpacesSpaceIdInstancesGetTest() throws ApiException {
        UUID spaceId = null;
        Object response = api.listInstancesUsingSpaceSpacesSpaceIdInstancesGet(spaceId);
        // TODO: test validations
    }

    /**
     * List Organization Spaces
     *
     * List spaces in an organization.  **Permissions:** Requires non-guest organization membership.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listOrganizationSpacesSpacesOrganizationsOrganizationIdGetTest() throws ApiException {
        UUID organizationId = null;
        Object response = api.listOrganizationSpacesSpacesOrganizationsOrganizationIdGet(organizationId);
        // TODO: test validations
    }

    /**
     * List Space Collaborators
     *
     * List space collaborators.  **Permissions:** Requires space collaborator access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSpaceCollaboratorsSpacesSpaceIdCollaboratorsGetTest() throws ApiException {
        UUID spaceId = null;
        Object response = api.listSpaceCollaboratorsSpacesSpaceIdCollaboratorsGet(spaceId);
        // TODO: test validations
    }

    /**
     * Move Record To Space
     *
     * Move a record into a target space.  **Permissions:** Requires instance admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void moveRecordToSpaceSpacesSpaceIdRecordAttachmentsPutTest() throws ApiException {
        UUID spaceId = null;
        Integer instanceDbSpaceId = null;
        AttachSpaceToRecordRequestBody attachSpaceToRecordRequestBody = null;
        UUID instanceId = null;
        Object response = api.moveRecordToSpaceSpacesSpaceIdRecordAttachmentsPut(spaceId, instanceDbSpaceId, attachSpaceToRecordRequestBody, instanceId);
        // TODO: test validations
    }

    /**
     * Remove Space Collaborator
     *
     * Remove an account or team collaborator from a space.  **Permissions:** Requires organization manager or admin access, or space admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSpaceCollaboratorSpacesSpaceIdCollaboratorsDeleteTest() throws ApiException {
        UUID spaceId = null;
        UUID accountId = null;
        UUID teamId = null;
        Object response = api.removeSpaceCollaboratorSpacesSpaceIdCollaboratorsDelete(spaceId, accountId, teamId);
        // TODO: test validations
    }

    /**
     * Update Space Collaborator
     *
     * Update a space collaborator&#39;s role.  **Permissions:** Requires organization manager or admin access, or space admin access. The account or team must already belong to the space organization.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpaceCollaboratorSpacesSpaceIdCollaboratorsPatchTest() throws ApiException {
        UUID spaceId = null;
        UpdateSpaceCollaboratorRequestBody updateSpaceCollaboratorRequestBody = null;
        Object response = api.updateSpaceCollaboratorSpacesSpaceIdCollaboratorsPatch(spaceId, updateSpaceCollaboratorRequestBody);
        // TODO: test validations
    }

    /**
     * Update Space
     *
     * Update a space&#39;s name or description.  **Permissions:** Requires organization manager or admin access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpaceSpacesSpaceIdPatchTest() throws ApiException {
        UUID spaceId = null;
        UpdateSpaceRequestBody updateSpaceRequestBody = null;
        Object response = api.updateSpaceSpacesSpaceIdPatch(spaceId, updateSpaceRequestBody);
        // TODO: test validations
    }

}
