/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.AddSpaceCollaboratorRequestBody;
import ai.lamin.lamin_api_client.model.AttachSpaceToRecordRequestBody;
import ai.lamin.lamin_api_client.model.CreateSpaceRequestBody;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import java.util.UUID;
import ai.lamin.lamin_api_client.model.UpdateSpaceCollaboratorRequestBody;
import ai.lamin.lamin_api_client.model.UpdateSpaceRequestBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpacesApi
 */
@Disabled
public class SpacesApiTest {

    private final SpacesApi api = new SpacesApi();

    /**
     * Add Space Collaborator
     *
     * Add a collaborator (account or team) to a space.  Parameters: - **space_id**: ID of the space to add the collaborator to - **body**: Request body containing collaborator details   - **account_id**: UUID of the account to add (mutually exclusive with team_id)   - **team_id**: UUID of the team to add (mutually exclusive with account_id)   - **role**: Role of the collaborator  Returns: - **201**: Collaborator added to space successfully - **400**: Invalid input (e.g., both account_id and team_id provided)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSpaceCollaboratorSpacesSpaceIdCollaboratorsPutTest() throws ApiException {
        UUID spaceId = null;
        AddSpaceCollaboratorRequestBody addSpaceCollaboratorRequestBody = null;
        String authorization = null;
        Object response = api.addSpaceCollaboratorSpacesSpaceIdCollaboratorsPut(spaceId, addSpaceCollaboratorRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Attach Space To Instance
     *
     * Attach a space to a specific instance.  Parameters: - **space_id**: ID of the space to attach - **instance_id**: UUID of the instance to attach the space to (from URL path)  Returns: - **200**: Space attached to instance successfully  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void attachSpaceToInstanceSpacesSpaceIdInstancesInstanceIdPutTest() throws ApiException {
        UUID spaceId = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.attachSpaceToInstanceSpacesSpaceIdInstancesInstanceIdPut(spaceId, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Create Space
     *
     * Create a new space.  Parameters: - **body**: Request body containing space details   - **name**: Name of the space   - **organization_id**: UUID of the organization   - **description**: Optional description of the space  Returns: - **201**: Space created successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSpaceSpacesPutTest() throws ApiException {
        CreateSpaceRequestBody createSpaceRequestBody = null;
        String authorization = null;
        Object response = api.createSpaceSpacesPut(createSpaceRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Delete Space
     *
     * Delete a space and detach it from the instance.  Parameters: - **space_id**: ID of the space to delete  Returns: - **200**: Space deleted successfully - **404**: Space not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSpaceSpacesSpaceIdDeleteTest() throws ApiException {
        UUID spaceId = null;
        String authorization = null;
        Object response = api.deleteSpaceSpacesSpaceIdDelete(spaceId, authorization);
        // TODO: test validations
    }

    /**
     * Detach Space From Instance
     *
     * Detach a space from a specific instance.  Parameters: - **space_id**: ID of the space to detach - **instance_id**: UUID of the instance to detach the space from (from URL path)  Returns: - **200**: Space detached from instance successfully  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void detachSpaceFromInstanceSpacesSpaceIdInstancesInstanceIdDeleteTest() throws ApiException {
        UUID spaceId = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.detachSpaceFromInstanceSpacesSpaceIdInstancesInstanceIdDelete(spaceId, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Get Space
     *
     * Get details of a specific space.  Parameters: - **space_id**: ID of the space to retrieve  Returns: - **200**: Space details retrieved successfully - **404**: Space not found
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpaceSpacesSpaceIdGetTest() throws ApiException {
        UUID spaceId = null;
        String authorization = null;
        Object response = api.getSpaceSpacesSpaceIdGet(spaceId, authorization);
        // TODO: test validations
    }

    /**
     * List Instance Spaces
     *
     * List all spaces attached to an instance.  Parameters: - **instance_id**: UUID of the instance to list spaces for (from URL path)  Returns: - **200**: List of spaces attached to the instance retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInstanceSpacesSpacesInstancesInstanceIdGetTest() throws ApiException {
        UUID instanceId = null;
        String authorization = null;
        Object response = api.listInstanceSpacesSpacesInstancesInstanceIdGet(instanceId, authorization);
        // TODO: test validations
    }

    /**
     * List Instances Using Space
     *
     * List all instances that have this space attached.  Parameters: - **space_id**: ID of the space to check  Returns: - **200**: List of instances using the space retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInstancesUsingSpaceSpacesSpaceIdInstancesGetTest() throws ApiException {
        UUID spaceId = null;
        String authorization = null;
        Object response = api.listInstancesUsingSpaceSpacesSpaceIdInstancesGet(spaceId, authorization);
        // TODO: test validations
    }

    /**
     * List Organization Spaces
     *
     * List all spaces in an organization.  Parameters: - **organization_id**: UUID of the organization to list spaces for  Returns: - **200**: List of spaces retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listOrganizationSpacesSpacesOrganizationsOrganizationIdGetTest() throws ApiException {
        UUID organizationId = null;
        String authorization = null;
        Object response = api.listOrganizationSpacesSpacesOrganizationsOrganizationIdGet(organizationId, authorization);
        // TODO: test validations
    }

    /**
     * List Space Collaborators
     *
     * List all collaborators of a space.  Parameters: - **space_id**: ID of the space to list collaborators for  Returns: - **200**: List of space collaborators retrieved successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSpaceCollaboratorsSpacesSpaceIdCollaboratorsGetTest() throws ApiException {
        UUID spaceId = null;
        String authorization = null;
        Object response = api.listSpaceCollaboratorsSpacesSpaceIdCollaboratorsGet(spaceId, authorization);
        // TODO: test validations
    }

    /**
     * Move Record To Space
     *
     * Move a record to a specific space.  Parameters: - **space_id**: ID of the space to move the record to - **body**: Request body containing record details   - **module_name**: Module name of the record   - **model_name**: Model name of the record   - **record_id**: ID of the record to move in the space - **instance_id**: UUID of the instance (from URL path) - **schema_id**: UUID of the schema (from URL path)  Returns: - **200**: Record moved to the space successfully  Requires admin access to the instance
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void moveRecordToSpaceSpacesSpaceIdRecordAttachmentsPutTest() throws ApiException {
        Integer instanceDbSpaceId = null;
        AttachSpaceToRecordRequestBody attachSpaceToRecordRequestBody = null;
        UUID instanceId = null;
        String authorization = null;
        Object response = api.moveRecordToSpaceSpacesSpaceIdRecordAttachmentsPut(instanceDbSpaceId, attachSpaceToRecordRequestBody, instanceId, authorization);
        // TODO: test validations
    }

    /**
     * Remove Space Collaborator
     *
     * Remove a collaborator (account or team) from a space.  Parameters: - **space_id**: ID of the space to remove the collaborator from - **account_id**: UUID of the account to remove (mutually exclusive with team_id) - **team_id**: UUID of the team to remove (mutually exclusive with account_id)  Returns: - **200**: Collaborator removed from space successfully - **400**: Invalid input (e.g., both account_id and team_id provided or neither provided)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSpaceCollaboratorSpacesSpaceIdCollaboratorsDeleteTest() throws ApiException {
        UUID spaceId = null;
        UUID accountId = null;
        UUID teamId = null;
        String authorization = null;
        Object response = api.removeSpaceCollaboratorSpacesSpaceIdCollaboratorsDelete(spaceId, accountId, teamId, authorization);
        // TODO: test validations
    }

    /**
     * Update Space Collaborator
     *
     * Update a collaborator&#39;s permissions in a space.  Parameters: - **space_id**: ID of the space to update the collaborator in - **body**: Request body containing collaborator details   - **account_id**: UUID of the account to update (mutually exclusive with team_id)   - **team_id**: UUID of the team to update (mutually exclusive with account_id)   - **role**: Role of the collaborator  Returns: - **200**: Collaborator updated successfully - **400**: Invalid input (e.g., both account_id and team_id provided) - **404**: Collaborator not found in space
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpaceCollaboratorSpacesSpaceIdCollaboratorsPatchTest() throws ApiException {
        UUID spaceId = null;
        UpdateSpaceCollaboratorRequestBody updateSpaceCollaboratorRequestBody = null;
        String authorization = null;
        Object response = api.updateSpaceCollaboratorSpacesSpaceIdCollaboratorsPatch(spaceId, updateSpaceCollaboratorRequestBody, authorization);
        // TODO: test validations
    }

    /**
     * Update Space
     *
     * Update a space&#39;s details.  Parameters: - **space_id**: ID of the space to update - **body**: Request body containing updated space details   - **name**: Optional new name for the space   - **description**: Optional new description for the space  Returns: - **200**: Space updated successfully
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpaceSpacesSpaceIdPatchTest() throws ApiException {
        UUID spaceId = null;
        UpdateSpaceRequestBody updateSpaceRequestBody = null;
        String authorization = null;
        Object response = api.updateSpaceSpacesSpaceIdPatch(spaceId, updateSpaceRequestBody, authorization);
        // TODO: test validations
    }

}
