/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.lamin.lamin_api_client.api;

import ai.lamin.lamin_api_client.ApiException;
import ai.lamin.lamin_api_client.model.CloudAccessRequest;
import ai.lamin.lamin_api_client.model.HTTPValidationError;
import ai.lamin.lamin_api_client.model.S3PermissionsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StoragesApi
 */
@Disabled
public class StoragesApiTest {

    private final StoragesApi api = new StoragesApi();

    /**
     * Get Cloud Access
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCloudAccessStoragesCredentialsPostTest() throws ApiException {
        CloudAccessRequest cloudAccessRequest = null;
        String authorization = null;
        Object response = api.getCloudAccessStoragesCredentialsPost(cloudAccessRequest, authorization);
        // TODO: test validations
    }

    /**
     * Get S3 File
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getS3FileStoragesS3FullPathGetTest() throws ApiException {
        String fullPath = null;
        String authorization = null;
        Object response = api.getS3FileStoragesS3FullPathGet(fullPath, authorization);
        // TODO: test validations
    }

    /**
     * Grant S3 Permissions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void grantS3PermissionsStoragesS3BucketNamePermissionsPutTest() throws ApiException {
        String bucketName = null;
        S3PermissionsRequest s3PermissionsRequest = null;
        String awsAccountId = null;
        String awsUserName = null;
        String authorization = null;
        Object response = api.grantS3PermissionsStoragesS3BucketNamePermissionsPut(bucketName, s3PermissionsRequest, awsAccountId, awsUserName, authorization);
        // TODO: test validations
    }

}
